# -*- coding: utf-8 -*-
"""BERT_Mask_Language_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxZASHNtKMzN3pIZvH0iRiSKz53RJudt

# model_name = "bert-base-uncased"

**1. Model Class (BertForMaskedLM):**

- This refers to the specific type of BERT model architecture you are using for a particular task.


- **BertForMaskedLM** is a class designed for masked language modeling, where the model tries to predict masked words in a sentence.


- These classes wrap the core BERT architecture and add task-specific layers, like classification heads or masked language modeling heads, so that BERT can be fine-tuned for different purposes.

- Think of these model classes as different versions or extensions of BERT tailored for specific NLP tasks.

- Some of the Known Model Classes

    - BERTforSequenceClassification: Classifiaction

    - BERTforTokenClassifcation  :  NER

    - BERTforQuestionAnswering : Q and A chatbot

    - BERTforMaksedLM : Find the Missing word

**2. Model Name ("bert-base-uncased"):**

- the pre-trained weights and configuration you are using for your model.

- "bert-base-uncased" is one of the many pre-trained models available from Hugging Face.

- It is a base version of BERT with 12 layers, and it is "uncased", meaning it does not distinguish between uppercase and lowercase letters (e.g., "Apple" and "apple" are treated the same).

- There are many different pre-trained model names available, such as "bert-large-uncased", "roberta-base", "gpt-2", etc.

- The model name specifies which set of pre-trained weights and tokenizer to load. This means when you use model_name = "bert-base-uncased", you're downloading a pre-trained model and tokenizer trained on a large corpus of data (like Wikipedia and BooksCorpus).

**Model Class (BertForMaskedLM) defines the task-specific architecture.**

**Model Name ("bert-base-uncased") defines which specific set of pre-trained weights and vocabulary you are loading into that architecture.**
"""

!pip install transformers

# import transformers
# dir(transformers)

from transformers import BertTokenizer, BertForMaskedLM
import torch

#Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForMaskedLM.from_pretrained(model_name)

sentence="I want to go [MASK]."
tokenized_input = tokenizer.encode_plus(sentence,
                                        return_tensors="pt",
                                        add_special_tokens=True)
tokenized_input
# 101 CLS
# 103 MASK
# 102 SEP
# [CLS], I, want, to, go, [MASK],.,[SEP]
# 1,1,1,1,1,1,1,1
# Model will get internally

sentence1="I want to go [MASK]."
sentence2="I want to go [MASK]."
tokenized_input_two = tokenizer.encode_plus(sentence1,sentence1,
                                        return_tensors="pt",
                                        add_special_tokens=True)
tokenized_input_two



"""**token_type_ids**

- will give the indication are we passing single senetnce or multiple sentences

- for single sentences token type ids all are zeros


"""



sentence="I want to go [MASK]."
tokenized_input_tf = tokenizer.encode_plus(sentence,
                                           return_tensors="tf",
                                           add_special_tokens=True)
tokenized_input_tf

tokenized_input_tf['input_ids'].numpy()

sentence="I want to go [MASK]."
tokenized_input_np = tokenizer.encode_plus(sentence,
                                           return_tensors="np",
                                           add_special_tokens=True)
tokenized_input_np

"""**Get tokens from token ids**"""

tokenized_input['input_ids'][0]  # pytorch tokens

tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'][0])

tokenizer._token_id

# Get the position of the masked token
masked_index = torch.where(tokenized_input["input_ids"] == tokenizer.mask_token_id)[1]
masked_index

tokenized_input

def val(**kwargs):
    print(kwargs)

val(name='naresh it',age='25')

def val(**kwargs):
    print(kwargs.items())

val(name='omkar')

"""**torch.no_grad**

- we are not using gradient calculations

- gradinet descent is used for updated weights that is for training purpose

- but for predictions again no need to calculation weights

- thats we are using no_grad
"""

tokenized_input

# It gives probability of each word to become a prediction
with torch.no_grad():
    outputs = model(**tokenized_input)

outputs.logits.shape

len(outputs.logits[0])

""""I want to go [MASK]."

[cls],I,want,to,go,[MASK],'.',[SEP] ===> Model

vocab=30522 words are there
[30522 probabilties]== max prob  ['Cls']
[30522 probabilites]=== max pron should match with  'I'
[30522 probabilites] === max prob word should match with 'want'
[30522 pr] === max prob word:home msk
"""

len(outputs.logits[0])

import numpy as np
np.argmax(outputs.logits[0][0])

import numpy as np
outputs.logits[0][0]  # 1 word vector
np.argmax(np.array(outputs.logits[0][0]))



tokenized_input

tokenizer

outputs.logits
import pandas as pd
import numpy as np
data=pd.DataFrame(outputs.logits[0])
data.columns=tokenizer.vocab.keys()
data.index=tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'][0])
data

# mask
import numpy as np
np.argmax(outputs.logits[0][5])

tokenizer.convert_ids_to_tokens([2188])

outputs.logits[0,5]

# Get the logits for the masked token
predictions = outputs.logits[0, masked_index, :]
predictions

masked_pred=outputs.logits[0,5]
masked_pred

masked_pred.unsqueeze(0)

import numpy as np
masked_pred=outputs.logits[0,5]
np.argmax(np.array(masked_pred))

# Get the top predictions
top_indices = torch.topk(masked_pred.unsqueeze(0), 3, dim=1).indices[0].tolist()
top_indices

tokenizer.convert_ids_to_tokens([2188,2067,2185])

from transformers import BertTokenizer, BertForMaskedLM
import torch

#Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForMaskedLM.from_pretrained(model_name)

# Define a function to predict masked words
def predict_masked_words(sentence):
    # Tokenize the input sentence
    tokenized_input = tokenizer.encode_plus(sentence, return_tensors="pt", add_special_tokens=True)

    # Get the position of the masked token
    masked_index = torch.where(tokenized_input["input_ids"] == tokenizer.mask_token_id)[1]

    # Predict the masked token
    with torch.no_grad():
        outputs = model(**tokenized_input)

    # Get the logits for the masked token
    predictions = outputs.logits[0, masked_index, :]

    # Get the top predictions
    top_indices = torch.topk(predictions, 1, dim=1).indices[0].tolist()

    # Convert token IDs to actual words
    predicted_tokens = [tokenizer.decode([index]) for index in top_indices]

    return predicted_tokens

# Example sentence with a masked word
input_sentence = "I want to go [MASK]."

# Predict masked words
predicted_words = predict_masked_words(input_sentence)

print("Predicted words:", predicted_words)

"""**Using Tensorflow**"""

from transformers import BertTokenizer, TFBertForMaskedLM
import tensorflow as tf

# Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForMaskedLM.from_pretrained(model_name)

# Define a function to predict masked words
def predict_masked_words(sentence):
    # Tokenize the input sentence
    tokenized_input = tokenizer.encode_plus(sentence, return_tensors="tf", add_special_tokens=True)

    # Get the position of the masked token
    masked_index = tf.where(tokenized_input["input_ids"] == tokenizer.mask_token_id)

    # Predict the masked token
    outputs = model(tokenized_input)

    # Get the logits for the masked token
    predictions = outputs.logits[0, masked_index[0, 1], :]

    # Get the top predictions
    top_indices = tf.math.top_k(predictions, k=1).indices.numpy()

    # Convert token IDs to actual words
    predicted_tokens = [tokenizer.decode([index]) for index in top_indices]

    return predicted_tokens

# Example sentence with a masked word
input_sentence = "I want to go [MASK]."

# Predict masked words
predicted_words = predict_masked_words(input_sentence)

print("Predicted words:", predicted_words)

"""# model_name = "bert-large-uncased"

"""

from transformers import BertTokenizer, BertForMaskedLM
import torch

# Load pre-trained BERT model and tokenizer
model_name = "bert-large-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForMaskedLM.from_pretrained(model_name)

# Define a function to predict masked words
def predict_masked_words(sentence):
    # Tokenize the input sentence
    tokenized_input = tokenizer.encode_plus(sentence, return_tensors="pt", add_special_tokens=True)

    # Get the position of the masked token
    masked_index = torch.where(tokenized_input["input_ids"] == tokenizer.mask_token_id)[1]

    # Predict the masked token
    with torch.no_grad():
        outputs = model(**tokenized_input)

    # Get the logits for the masked token
    predictions = outputs.logits[0, masked_index, :]

    # Get the top 5 predictions
    top_5_indices = torch.topk(predictions, 5, dim=1).indices[0].tolist()

    # Convert token IDs to actual words
    predicted_tokens = [tokenizer.decode([index]) for index in top_5_indices]

    return predicted_tokens

# Example sentence with a masked word
input_sentence = "Are you going to [MASK]."
# Predict masked words
predicted_words = predict_masked_words(input_sentence)

print("Predicted words:", predicted_words)



"""# model_name = bert-base-multilingual-uncased"""

from transformers import BertTokenizer, BertForMaskedLM
import torch

# Load pre-trained BERT model and tokenizer
model_name = "bert-base-multilingual-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForMaskedLM.from_pretrained(model_name)

# Define a function to predict masked words
def predict_masked_words(sentence):
    # Tokenize the input sentence
    tokenized_input = tokenizer.encode_plus(sentence, return_tensors="pt", add_special_tokens=True)

    # Get the position of the masked token
    masked_index = torch.where(tokenized_input["input_ids"] == tokenizer.mask_token_id)[1]

    # Predict the masked token
    with torch.no_grad():
        outputs = model(**tokenized_input)

    # Get the logits for the masked token
    predictions = outputs.logits[0, masked_index, :]

    # Get the top 5 predictions
    top_5_indices = torch.topk(predictions, 5, dim=1).indices[0].tolist()

    # Convert token IDs to actual words
    predicted_tokens = [tokenizer.decode([index]) for index in top_5_indices]

    return predicted_tokens

# Example sentence with a masked word
input_sentence = "What is your favorite [MASK]?"
# Predict masked words
predicted_words = predict_masked_words(input_sentence)

print("Predicted words:", predicted_words)



