# -*- coding: utf-8 -*-
"""Agentic RAG llama GROQ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QwmW50OEPXhXkBLPxcpx7TiMcDXJ5pe5

<h1>Agentic RAG llama GROQ</h1>
<center><b>RAG : Retrieval Augmented Generation</b></center>
<b>Langchain-groq</b>

**Step-1: Install the packages**
"""

!pip install langchain langchain-groq langchain-community

pip install pypdf

pip install chromadb

"""**Step-2: Retrive LLM model using groq**"""

from langchain_groq import ChatGroq
groq_api="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"   # Groq API Key - https://console.groq.com/keys

llm = ChatGroq(
    api_key=groq_api,
    model="llama-3.3-70b-versatile",
    temperature=0.7,
    max_tokens=512
)
llm

"""**Step-3: Load the pdf**"""

from langchain.document_loaders import PyPDFLoader
pdf_path = "/content/nareshiT_context2.pdf"
loader = PyPDFLoader(pdf_path)
documents = loader.load()

"""**Step-4: Split into Text**"""

from langchain.text_splitter import RecursiveCharacterTextSplitter
# ------------------ SPLIT ------------------
splitter = RecursiveCharacterTextSplitter(
    chunk_size=800, # Each split size
    chunk_overlap=200 # 200 characters Overlap
)
docs = splitter.split_documents(documents)
print(docs)

"""**Step-5: Divide text into Embeddings and store in vector database**

"""

# ------------------ EMBEDDINGS + VECTORSTORE ------------------
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma   # Chroma Database
embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

vectordb = Chroma.from_documents(
    documents=docs,  # PDF
    embedding=embeddings, # Model
)
vectordb.persist()

retriever = vectordb.as_retriever(search_kwargs={"k": 10})  # 4 top chunks  db : Database Everytime we need to get 10 Outputs

"""**Step-6: Develop a Prompt**"""

# ------------------ CUSTOM PROMPT ------------------
system_prompt = """
You are a helpful **College Administrator at Naresh IT**.
Your role is to warmly explain training programs, trainers, schedules, placements, and facilities
to new students who are joining the institute.

Context rules:
- Use only the provided CONTEXT chunks from the retriever.
- Explain in a clear, welcoming, and professional tone.
- Highlight key details like trainer names, course schedules, fees, infrastructure, and placement support.
- If multiple trainers or batches are mentioned, clarify them politely.
- Do not make up information beyond the context.
- When useful, mention the chunk/page metadata as your reference.
"""

"""**Step-7: Create a PromptTemplate**"""

from langchain.prompts import PromptTemplate
from langchain.prompts import PromptTemplate

prompt_template = PromptTemplate(
    template="""
You are a helpful **College Administrator at Naresh IT**.
Your role is to warmly explain training programs, trainers, schedules, placements, and facilities
to new students who are joining the institute.

Context rules:
- Use only the provided CONTEXT chunks from the retriever.
- Explain in a clear, welcoming, and professional tone.
- Highlight key details like trainer names, course schedules, fees, infrastructure, and placement support.
- If multiple trainers or batches are mentioned, clarify them politely.
- Do not make up information beyond the context.
- When useful, mention the chunk/page metadata as your reference.

CONTEXT:
{context}

QUESTION:
{question}

Answer as the College Administrator.
""",
    input_variables=["context", "question"]
)

"""**Step-8: Build Retrieval QA**"""

from langchain.chains import RetrievalQA
retrieval_qa = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever, # Retriver : Vector Database ; Vector Databse gives 10 answers
    chain_type="stuff", # Stuff : Combine all
    chain_type_kwargs={"prompt": prompt_template}
)
# LLM model will get 10 answers from database and combine based on prompt

"""**Step-9: Ask the Question**"""

query = "Provide me omkar sir class zoom link"
response = retrieval_qa.run(query)

print("\n--- Model Answer ---\n")
print(response)

query = "Provide me omkar sir reviews"
response = retrieval_qa.run(query)

print("\n--- Model Answer ---\n")
print(response)

query = "What are the latest python classes timings"
response = retrieval_qa.run(query)

print("\n--- Model Answer ---\n")
print(response)

"""**Its giving information only from document this is Standard RAG appraoch**

**If we connect any API calls then fetch the data this indicates AGENTIC Behaviour**

## Agentic RAG

**Step-10: Fetch the data from url**
"""

from bs4 import BeautifulSoup # Web Scrapping
import requests

course_schedule_url = "https://nareshit.in/course-schedule/"
def fetch_trainer_from_web(query: str):
    """
    Fetch ALL trainer/course details from NareshIT course-schedule page.
    Input: trainer name or course name as plain text.
    Returns: A student-friendly description string with all matches.
    """
    resp = requests.get(course_schedule_url, timeout=10)
    if resp.status_code != 200:
        return f"Could not reach schedule page (status code {resp.status_code})."

    soup = BeautifulSoup(resp.text, "html.parser")
    rows = soup.find_all("tr")

    matches = []
    for row in rows:
        cols = [td.get_text(strip=True) for td in row.find_all("td")]
        if any(query.lower() in c.lower() for c in cols):
            course = cols[0] if len(cols)>0 else "Unknown"
            trainer = cols[1] if len(cols)>1 else "Unknown"
            date = cols[2] if len(cols)>2 else "Unknown"
            time = cols[3] if len(cols)>3 else "Unknown"
            matches.append(
                f"Course: {course}\n"
                f"Trainer: {trainer}\n"
                f"Start Date: {date}\n"
                f"Time: {time}\n"
            )

    if not matches:
        return f"No matching course or trainer found for '{query}' on NareshIT schedule."
    return "\n---\n".join(matches)

"""**Step-11: Course Schedule and Trainer Fetcher Tool Definition**"""

from langchain.agents import initialize_agent, Tool, AgentType
trainer_tool = Tool(
    name="Course Schedule Web Fetcher",
    func=fetch_trainer_from_web,
    description=(
        "Use this tool to answer queries about courses, trainers, or session schedules "
        "at Naresh IT. Input can be a course name (like 'Python') or trainer name."
    )
)

"""**Step-12: Defining a Document Retrieval Tool**"""

retriever_tool = Tool(
    name="Document Retriever",
    func=lambda q: retrieval_qa.run(q), # Database Name : retrieval_qa
    description="Answer queries using NareshIT training documents."
)

"""**Step-13: Initialise the agent**

"""

tools = [retriever_tool, trainer_tool]

# Initialize agent with a more flexible agent type
agent = initialize_agent(
    tools=tools,
    llm=llm,
    agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,  # works with plain text tools ; Zero Shot : means NO training / NO examples
    verbose=True
)

"""**Step-14: Provid the Instructions to agent**"""

system_instruction = """
You are a helpful College Administrator at Naresh IT.
- If the student asks about sessions, trainers, or course schedules, first try the Document Retriever tool (PDF).
- If no relevant info is found, use the Course Schedule Web Fetcher tool.
- Always provide a friendly, student-facing final answer.
"""

"""**Step-15: Start Query**"""

query = "Tell me about upcoming session on python."
response = agent.run(f"{system_instruction}\n\nQuestion: {query}")

print("\n--- Admin Answer ---\n", response)

query = "Provide me Omkar sir upcoming class zoom link."
response = agent.run(f"{system_instruction}\n\nQuestion: {query}")

print("\n--- Admin Answer ---\n", response)

# from langchain.agents import initialize_agent, Tool, AgentType
# from langchain.chains import RetrievalQA
# from bs4 import BeautifulSoup
# import requests

# course_schedule_url = "https://nareshit.in/course-schedule/"

# # 1Scraper tool
# def fetch_trainer_from_web(query: str):
#     """
#     Fetch ALL trainer/course details from NareshIT course-schedule page.
#     Input: trainer name or course name as plain text.
#     Returns: A student-friendly description string with all matches.
#     """
#     resp = requests.get(course_schedule_url, timeout=10)
#     if resp.status_code != 200:
#         return f"Could not reach schedule page (status code {resp.status_code})."

#     soup = BeautifulSoup(resp.text, "html.parser")
#     rows = soup.find_all("tr")

#     matches = []
#     for row in rows:
#         cols = [td.get_text(strip=True) for td in row.find_all("td")]
#         if any(query.lower() in c.lower() for c in cols):
#             course = cols[0] if len(cols)>0 else "Unknown"
#             trainer = cols[1] if len(cols)>1 else "Unknown"
#             date = cols[2] if len(cols)>2 else "Unknown"
#             time = cols[3] if len(cols)>3 else "Unknown"
#             matches.append(
#                 f"Course: {course}\n"
#                 f"Trainer: {trainer}\n"
#                 f"Start Date: {date}\n"
#                 f"Time: {time}\n"
#             )

#     if not matches:
#         return f"No matching course or trainer found for '{query}' on NareshIT schedule."
#     return "\n---\n".join(matches)

# trainer_tool = Tool(
#     name="Course Schedule Web Fetcher",
#     func=fetch_trainer_from_web,
#     description=(
#         "Use this tool to answer queries about courses, trainers, or session schedules "
#         "at Naresh IT. Input can be a course name (like 'Python') or trainer name."
#     )
# )

# # Optional document retriever (kept from your code)
# retriever_chain = RetrievalQA.from_chain_type(
#     llm=llm,
#     retriever=retriever,
#     chain_type="stuff"
# )
# retriever_tool = Tool(
#     name="Document Retriever",
#     func=lambda q: retriever_chain.run(q),
#     description="Answer queries using NareshIT training documents."
# )

# tools = [retriever_tool, trainer_tool]

# # 3Initialize agent with a more flexible agent type
# agent = initialize_agent(
#     tools=tools,
#     llm=llm,
#     agent=AgentType.CHAT_ZERO_SHOT_REACT_DESCRIPTION,  # works with plain text tools
#     verbose=True
# )

# # System instruction
# system_instruction = """
# You are a helpful College Administrator at Naresh IT.
# - If the student asks about sessions, trainers, or course schedules, ALWAYS call the Course Schedule Web Fetcher tool.
# - If the student asks about institute profile, history, placement, or syllabus, use the Document Retriever.
# - Always give a friendly, student-facing response with final information.
# """

# #  Query
# query = "Tell me about upcoming session on python."
# response = agent.run(f"{system_instruction}\n\nQuestion: {query}")

# print("\n--- Admin Answer ---\n", response)

"""## Spot ON-1

- Difference between RecursiveCharacterTextSplitter vs CharacterTextSplitter

**1. Character-level splitting**

Splits text into chunks of fixed character length (e.g., 500 characters per chunk).

- Pros:

    - Simple to implement.

- Cons:

    - Can cut sentences in half, losing semantic meaning.

    - Chunks might be arbitrary, making embeddings less semantically meaningful.

**2. Recursive splitting (hierarchical)**

Splits text intelligently, e.g.:

    - First by document → sections

    - Then paragraphs

    - Then sentences, if needed.


- Pros:

    - Preserves semantic units (sentences/paragraphs).

    - Embeddings capture meaningful context, improving RAG performance.

- Cons:

    - Slightly more complex to implement.

"""

# Example text
text = """
Artificial intelligence (AI) is the simulation of human intelligence in machines. These machines are programmed to think like humans and mimic their actions. AI has applications in many industries, including healthcare, finance, and transportation.

Machine learning is a subset of AI that allows systems to learn and improve from experience without being explicitly programmed. Deep learning, a further subset of machine learning, uses neural networks to model complex patterns in data.
"""

# -------- 1. Character-level splitting --------
def split_by_char(text, chunk_size=100):
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

char_chunks = split_by_char(text, chunk_size=100)
print("Character-level chunks:\n")
for i, chunk in enumerate(char_chunks, 1):
    print(f"Chunk {i}:\n{chunk}\n")

# -------- 2. Recursive splitting (paragraph → sentence) --------
import re

def split_by_paragraph_and_sentence(text):
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    sentence_chunks = []
    for para in paragraphs:
        # Split paragraph into sentences
        sentences = re.split(r'(?<=[.!?])\s+', para)
        sentence_chunks.extend(sentences)
    return sentence_chunks

recursive_chunks = split_by_paragraph_and_sentence(text)
print("\nRecursive chunks (paragraph → sentence):\n")
for i, chunk in enumerate(recursive_chunks, 1):
    print(f"Chunk {i}:\n{chunk}\n")

"""## SPOT-ON 2:

- Difference between VectorDBQA, RetrievalQA, and Multi-RetrievalQA

| QA Type               | Data Source(s)                                   | Retrieval Method                       | Use Case / Notes                                                                    | Cloud DB Support                                                       |
| --------------------- | ------------------------------------------------ | -------------------------------------- | ----------------------------------------------------------------------------------- | ---------------------------------------------------------------------- |
| **VectorDBQA**        | Vector database (e.g., Pinecone, FAISS, Chroma)  | Vector similarity search               | Best for large text corpora already embedded; retrieves semantically similar chunks | Usually not direct; can embed cloud DB content first                   |
| **RetrievalQA**       | Single source (documents, PDFs, DBs)             | Retriever queries source               | Works with one knowledge base; simple setup for focused domains                     | ✅ Yes – can query Azure SQL, AWS RDS, DynamoDB, etc.                   |
| **Multi-RetrievalQA** | Multiple sources (documents, PDFs, multiple DBs) | Multiple retrievers, aggregate results | Useful for heterogeneous knowledge bases; combines answers from several sources     | ✅ Yes – each retriever can target a different cloud DB or vector store |

## SPOT-ON 3:

Chain types

- stuff

- MAP Reduce

- Refine

- Map Rerank


| Chain Type     | How It Works                                                                                                                    | Pros ✅                                              | Cons ❌                                                      | Use Case                         |
| -------------- | ------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------- | ----------------------------------------------------------- | -------------------------------- |
| **Stuff**      | All retrieved documents are **“stuffed” into the prompt** and sent to the LLM in one go.                                        | Simple, fast, easy                                  | Doesn’t scale if many docs (token limit risk)               | Small # of short docs            |
| **Map Reduce** | **Map:** LLM processes each doc individually → partial answers. <br> **Reduce:** Combine partial answers into one final answer. | Scales to large docs, parallelizable                | Slower, multiple LLM calls                                  | Large corpora or long docs       |
| **Refine**     | Start with first doc → LLM drafts answer → iteratively updates/refines answer with each new doc.                                | Produces detailed, context-aware answers            | Sequential (slower), answer may depend heavily on doc order | When accuracy/nuance is critical |
| **Map Rerank** | LLM evaluates each doc separately → scores/ranks relevance → selects best doc/answer.                                           | Helps pick the *most relevant* answer, avoids noise | Doesn’t combine info from multiple docs well                | When precision > recall          |

Stuff → “Throw everything at once.”

Map Reduce → “Summarize each piece, then combine summaries.”

Refine → “Keep improving the answer as more docs arrive.”

Map Rerank → “Pick the best single answer from many candidates.”
"""