# -*- coding: utf-8 -*-
"""Multi Modal RAG Extract Images PART - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATMEHf1b_pJuSbvVDDYrI7fdpYL5rSgz

# Step - 1: Install the packages
"""

# Install required packages
!pip install langchain langchain-community pillow pymupdf python-dotenv  # Packages
'''
langchain             : RAG Framework like Memory ; Chain ; Tools ; Agents
langchain-community   : To connect with external sources like pdf ; dox ; images
pillow                : To work with images like Load & display the images
pymupdf               : To work with pdf files
python-dotenv         : To load the environment variables like hiding keys
'''

!pip install langchain-groq

pip install -U langchain-cohere

"""# Step - 2: Import packages"""

pip install langchain-cohere

import fitz  # PyMuPDF
from PIL import Image
import io
import os
from dotenv import load_dotenv

import google.generativeai as genai

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.documents import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_cohere import ChatCohere, CohereEmbeddings

load_dotenv()

"""# Step-3: Read the attention_is_all_you_need.pdf"""

!wget https://arxiv.org/pdf/1706.03762 # https://arxiv.org/pdf/1706.03762 : Is a research paper file link
!mv 1706.03762 attention_is_all_you_need.pdf

'''
attention_is_all_you_need.pdf : Is used to demonstrate the RAG framework & also helps in downloading PDF files from ONLINE
'''

pdf_file=fitz.open('attention_is_all_you_need.pdf') # In order to know how many pages are there in the pdf we need to open the pdf file

len(pdf_file) # Length : 15 pages

page = pdf_file[1]
page

text = page.get_text().strip()
 print(text)
 # Present in the pdf

"""<h1><b>Image Page</b></h1>"""

page = pdf_file[2]  # Image is available in 3rd page of pdf but in python it's index = 2
text = page.get_text().strip()
print(text)
# But we're not printing image we're ONLY extracting the TEXT from page 3

images = page.get_images(full=True)
images # The output indicates only 1 image is available in that page

len(images) # Means in this page only 1 image is available*

images[0] # 1 image

# xref : It is a reference number in PDF or a unique id of the image

images[0][0] # LIST INDEXING 1 image = 0 ; Extract the 1st number "128" in image so index = 0

images[0][1]

images[0][3]

images[0][2]

xref=images[0][0]
xref # This is called the hyperlink of the image

# xref : It is a reference number in PDF or a unique id of the image

# extract the image
base_image = pdf_file.extract_image(xref)
image_bytes = base_image["image"] # image is encoded in bytes data
#image_bytes

image_bytes # Image data is encoded in the form of bytes

"""<h1><b>Display the image</b></h1>"""

from PIL import Image # PIL : Pillow Package
import io  # io Package

# convert bytes to a PIL image
image = Image.open(io.BytesIO(image_bytes))

# show the image (opens with default image viewer or inline in Jupyter)
image

"""# Extract the Text using Gemini"""

from google.colab import userdata
api_key=userdata.get('gemini_Api')

genai.configure(api_key=api_key)
model = genai.GenerativeModel(model_name="gemini-2.5-flash")

response = model.generate_content([image, "You are an assistant tasked with summarizing tables, images and text for retrieval. \
    These summaries will be embedded and used to retrieve the raw text or table elements \
    Give a concise summary of the table or text that is well optimized for retrieval. Table or text or image:"])
response

text=response.text
print(text)

"""# All together : Automate Code
Means all the above 👆 individual cells in 1 single code cell
"""

text_data = []
img_data = []
with fitz.open('attention_is_all_you_need.pdf') as pdf_file:
    # Create a directory to store the images
    if not os.path.exists("extracted_images"):
        os.makedirs("extracted_images") # Saving the images in extracted_images folder

    # Loop through every page in the PDF
    for page_number in range(len(pdf_file)): # 15 papges in the pdf
        page = pdf_file[page_number]

        # Get the text on page
        text = page.get_text().strip() # Extarcted the text
        text_data.append({"response": text, "name": page_number+1}) # We appended the text data in a list
        # Get the list of images on the page
        images = page.get_images(full=True) # Append images in a list

        # Loop through all images found on the page
        for image_index, img in enumerate(images, start=0):
            xref = img[0]  # Get the XREF of the image
            base_image = pdf_file.extract_image(xref)  # Extract the image
            image_bytes = base_image["image"]  # Get the image bytes
            image_ext = base_image["ext"]  # Get the image extension

            # Load the image using PIL and save it
            image = Image.open(io.BytesIO(image_bytes))
            image.save(f"extracted_images/image_{page_number+1}_{image_index+1}.{image_ext}")
            # Saving the image file

for img in os.listdir("extracted_images"):
    image = Image.open(f"extracted_images/{img}")
    response = model.generate_content([image, "You are an assistant tasked with summarizing tables, images and text for retrieval. \
    These summaries will be embedded and used to retrieve the raw text or table elements \
    Give a concise summary of the table or text that is well optimized for retrieval. Table or text or image:"])
    img_data.append({"response": response.text, "name": img})

img_data

len(text_data)