# -*- coding: utf-8 -*-
"""Langsmith.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNLaefHJm7gKpdUdfrqqz_VYOOYLp75U

<h1><center>LangSmith</center></h1>
<h1><center>LangSmith</center>
<center><b>From Prompt to Production</b></center>

https://docs.langchain.com/oss/python/integrations/providers/groq

https://smith.langchain.com/o/1a1170d3-ddd1-46c3-b49e-628e8d7dd745/projects

https://reference.langchain.com/python/langchain_core/output_parsers/#langchain_core.output_parsers

https://console.groq.com/playground

https://groq.com/

https://openrouter.ai/rankings

https://docs.langchain.com/oss/python/integrations/chat/groq

https://docs.langchain.com/oss/python/integrations/providers/groq
"""

!pip install langchain-groq

"""# Chat Models"""

from langchain_groq import ChatGroq

"""ChatGroq is a method to access the llm model using API key

chatgroq(
    apikey,
    model name,
    temperature  # Model thinking power 0 - Straight answer ; 1 - Model thinking
    
)

https://docs.langchain.com/oss/python/integrations/chat/groq

Model Llama 3.3 70B
- llama-3.3-70b-versatile
"""

from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=50,
    # other params...
)

llm.invoke('Who are the top 5 cricketers in INDIA ?')

llm.invoke('Tell me about a guy named Hemant Katta')

llm.invoke('Who are the top 5 cricketers in INDIA ?').content

"""Controlled model with 50 tokens so till "Kohli is"
"""

from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None,
    # other params...
)

llm.invoke('Who are the top 5 cricketers in INDIA ?').content

print(llm.invoke('Who are the top 5 cricketers in INDIA ?').content)

llm.invoke('Who are the top 5 cricketers in INDIA ?').content

!pip install langchain-core

import langchain_core

dir(langchain_core)

from langchain_core.output_parsers import StrOutputParser

"""- We'll ask the question to llama model
- Answer not cleaned
- It'll go to Parser
"""

from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None
)

parser=StrOutputParser()

chain=llm|parser
chain.invoke('Tell about a poem on kid')

from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None
)

parser=StrOutputParser()

chain=llm|parser
response=chain.invoke('Tell about a poem on kid')

print(response)

chain=llm|parser
response=chain.invoke('Tell about a horror story')

print(response)

chain=llm|parser
response=chain.invoke('Tell about a bed time story')

print(response)

"""What ever we did that we want to store & want to check later i.e Langsmith
- How many question we asked

https://smith.langchain.com/o/1a1170d3-ddd1-46c3-b49e-628e8d7dd745?paginationModel=%7B%22pageIndex%22%3A0%2C%22pageSize%22%3A5%7D
"""

LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="Testing LLM Application"

# Creating Environmental Variable
import os
os.environ["LANGCHAIN_API_KEY"]=LANGCHAIN_API_KEY
os.environ["LANGCHAIN_PROJECT"]=LANGCHAIN_PROJECT
os.environ["LANGCHAIN_TRACING_V2"]='true'

# What ever we do in this it is visible in LangSmith

from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None
)

parser=StrOutputParser()

chain=llm|parser
response=chain.invoke('Tell about a poem on kid')

print(response)

# Creating Environmental Variable
import os
os.environ["LANGCHAIN_API_KEY"]=LANGCHAIN_API_KEY
os.environ["LANGCHAIN_PROJECT"]=LANGCHAIN_PROJECT
os.environ["LANGCHAIN_TRACING_V2"]='true'

# What ever we do in this it is visible in LangSmith

from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None
)

parser=StrOutputParser()

chain=llm|parser
response=chain.invoke('Tell a horror story')

print(response)

LANGCHAIN_API_KEY="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"
LANGCHAIN_PROJECT="Workshop"

# Creating Environmental Variable
import os
os.environ["LANGSMITH_API_KEY"]="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"
os.environ["LANGSMITH_PROJECT"]="Workshop"
os.environ["LANGSMITH_TRACING_V2"]='true'

# What ever we do in this it is visible in LangSmith

from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None
)

parser=StrOutputParser()

chain=llm|parser
response=chain.invoke('Tell a horror story')

print(response)

# Creating Environmental Variable
import os
os.environ["LANGSMITH_API_KEY"]="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"
os.environ["LANGSMITH_PROJECT"]="Workshop"
os.environ["LANGSMITH_TRACING_V2"]='true'

# What ever we do in this it is visible in LangSmith

from langchain_core.output_parsers import StrOutputParser
from langchain_groq import ChatGroq

llm = ChatGroq(
    api_key="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",
    model="llama-3.3-70b-versatile",
    temperature=0,
    max_tokens=None
)

parser=StrOutputParser()

chain=llm|parser
response=chain.invoke('Tell a horror story')

print(response)